ALTER TABLE juegos ADD COLUMN IF NOT EXISTS popup_activo BOOLEAN DEFAULT FALSE;
ALTER TABLE juegos ADD COLUMN IF NOT EXISTS popup_titulo TEXT;
ALTER TABLE juegos ADD COLUMN IF NOT EXISTS popup_mensaje TEXT;
ALTER TABLE juegos ADD COLUMN IF NOT EXISTS popup_imagen TEXT;
